table Orders
	lineageTag: e4b1c712-1e56-4b0f-95a3-c102de81a2cc

	measure 'Total Sales' = SUM(Orders[Sales])
		lineageTag: e6cea8bf-d327-40ba-af30-074798111bb9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = sum(Orders[Profit])
		lineageTag: f1d7c5bc-714b-4fbb-b1b8-173dc939ae6a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 9d02dffc-6da7-4698-9948-266d295b9c29
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: a82d1701-de16-4f32-ac99-30a6962ad0a0
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9eebb0c2-d10c-49b4-ad50-a4c0fcd6a686
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: ab67569f-92b1-4532-af95-7ea3ec9dd0b5
			defaultHierarchy: LocalDateTable_7babbafd-9c3f-43c2-94a2-a0b71d81314f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f1b70487-63f6-41b2-aecd-a39bab834e30
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: b6a96f1f-ae10-47c1-a48d-c30dd8183e40
			defaultHierarchy: LocalDateTable_7e2df2f2-8d36-411b-9ae4-f1985380bb03.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 95887c28-686c-4a3e-8c61-71c05649f4ec
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 9d56ed5f-af6c-460c-99ba-1d8faf9ee938
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 368390b0-de12-45c7-b572-1c5c4eada57d
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 731dad36-c2e8-43a2-bdd5-b8213a0c9b9b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: 03f9d1a5-75db-4862-abc4-14eed4f66dcf
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 1fdadca8-0e13-498f-8220-695358a2094e
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: 2e8cf292-36a8-4d7c-8c71-d6064f4c15ff
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: eb89e646-e33d-411b-882f-d0e790b5a950
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 5a79bede-5e9c-4184-9357-82b9b04bc96d
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 2fd5d00e-7163-4453-a6cc-72de29f6030d
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: b195e28a-6e29-43b7-9e81-6321176511bd
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 4a69fe77-3e05-4bc6-99c1-9b6346c27fba
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 89415b64-439c-4cee-95c5-ad3d49245fd0
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 4f042149-d354-47e2-bd3f-92fa38ecf736
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 2b76d802-90ec-4e97-8ee1-b866e41e731d
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: fcc34167-969a-467e-ba5e-30d55807043b
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 1f001313-fd6d-4977-b39d-560be3a8f0ab
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\samplesuperstore\sample_superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

